Contact form addition to portfolio Website
Newtayo/Portfolio-Setup pull request #7
Opened 2023-01-17 21:28 UTC by Newtayo

The following features has been updated on the portfolio mobile website

- Added a contact form section for users to send in their requests.
- The contact form has been integrated with formspree to enable it store information.
- The submit button in the contact form section now has a hover effect

2023-01-17 22:08 UTC, NahnahAJ requested changes
Hi @Newtayo and @Adholah96, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media2.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif"/>

## Highlights
- Good use of GitHub flow :heavy_check_mark: 
- Meaningful commit messages :heavy_check_mark: 
- No linter errors :heavy_check_mark: 
- Project well documented :heavy_check_mark: 
- Nice design :fire: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
N / A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 22:08 UTC, NahnahAJ commented on style.css
> +    cursor: pointer;
- Great job so far :muscle: Your project is almost complete. There is just something small you have to do to proceed to the next milestone :smile: 
- [ ] I noticed that your button is missing the right button interaction styles that the template you picked provided you with. I have attached a screenshot below :wink: 
- The Figma Design
![image](https://user-images.githubusercontent.com/102699958/213021246-406ef105-2fd7-4754-9989-3f9298489598.png)
- Your Design in all of these states
![image](https://user-images.githubusercontent.com/102699958/213021491-fbfb08eb-5b2c-434d-b3ae-d97281c1b56e.png)
- [ ] Please try to stick to the Figma design as much as possible. This includes colors, margins, padding etc. :wink:

2023-01-18 08:55 UTC, Newtayo commented
Button Feature such as hover, enabled and disabled button have been added to the buttons

2023-01-18 09:08 UTC, amejid approved these changes
Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/RltjLEzzB87ErJdxHz/giphy.gif"/>

## Highlights
- Linter checks passing :heavy_check_mark: 
- Formspree working as expected :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 09:49 UTC, merged